<?php
include('../incl/inc_header.php')
?>
<html>
    <title></title>
    <head></head>
    <body>
        <header></header>
        <main></main>
        <footer></footer>
    </body>
</html>